spring:

  application:
    name: FitLog-TDS

  datasource:
    url: jdbc:mysql://localhost:3306/fitlogdb?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

api:
  security:
    token:
      secret: 123
    google:
      client-id: 870642638434-tmj6b015q6t07elp2cpdp6a05mivbaj6.apps.googleusercontent.com